config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :find_task, only: [:show, :edit, :update, :destroy]
    
    def index 
        if params[:category].blank?
            @tasks = Task.all.order("created_at DESC")
        else
            @category_id = Category.find_by(name: params[:category]).id
            @tasks = Task.where(category_id: @category_id).order('created_at DESC')
        end
    end

    def show
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new(task_params)

        if @task.save
            redirect_to @task
        else
            render "New"
        end
    end

    def edit
    end

    def update
        if @task.update(task_params)
            redirect_to @task
        else
            render "Edit"
        end
    end

    def destroy
        @task.destroy
        redirect_to root_path
    end

    private

    def task_params
        params.require(:task).permit(:title, :description, :company, :url, :category_id)
    end

    def find_task
        @task = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Task %Manager 
  = csrf_meta_tags 
  = csp_meta_tag 
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 

%body
  - Category.all.each do |category|
    = link_to category.name, tasks_path(category: category.name)

  =yield

app/views/tasks/_form.html.haml
= simple_form_for(@task, html: {class: 'form-horizontal'}) do |f|
    = f.collection_select :category_id, Category.all, :id, :name, {prompt: 'Choose a Category for your task'}
    = f.input :title, label: "Task title"
    = f.input :description, label: "Task description"
    = f.input :company, label: "Your company"
    = f.input :url, label: "Link to task"
    %br/
    = f.button :submit

app/views/tasks/edit.html.haml
%h1 New Task

= render 'form'

= link_to "Back", root_path

app/views/tasks/index.html.haml
- @tasks.each do |task|
    %h2= link_to task.title, task
    %p= task.company

= link_to "New Task", new_task_path

app/views/tasks/new.html.haml
%h1 New Task

= render 'form'

= link_to "Back", root_path

app/views/tasks/show.html.haml
%h1= @task.title

%p= @task.description
%p= @task.company
%p= @task.url

= link_to "Home", root_path
= link_to "Edit", edit_task_path(@task)
= link_to "Delete", task_path(@task), method: :delete, data:  {confirm: "Are you sure?"}